// Generated by CoffeeScript 1.11.1
(function() {
  SCRIB.Testing = (function() {
    function Testing() {
      console.log("All tests have passed!");
      document.getElementById("text").innerHTML = "All Tests Have Passed!";
    }

    Testing.prototype.ASSERT = function(b) {
      var err;
      if (!b) {
        err = new Error();
        console.log(err.stack);
        throw new Error("Assertion Failed!");
      }
    };

    return Testing;

  })();

  new SCRIB.Testing();

}).call(this);

//# sourceMappingURL=testing.js.map
